apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: the-platform-certs
  namespace: the-platform
spec:
  secretName: the-platform-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ok.platform.apk8s.dev
  dnsNames:
    - ok.platform.apk8s.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ok.platform.apk8s.dev