apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
parameters:
  blockPool: replicapool
  clusterNamespace: rook-ceph
  fstype: xfs
provisioner: ceph.rook.io/block
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cluster-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
  dataPools:
    - replicated:
        size: 1
  metadataServer:
    activeCount: 1
    activeStandby: true